package com.tripmaven.members.model;


import java.time.LocalDateTime;
import java.util.Date;


import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * 회원테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Table(name = "Members")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamicInsert
public class MembersEntity {

	/** 회원 고유 번호. */
	@Id
	@SequenceGenerator(name="seq_members",sequenceName = "seq_members", allocationSize = 1,initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "seq_members")
	private long id;

	/** 이메일. */
	@Column(nullable = false, length = 50)
	private String email;

	/** 이름. */
	@Column(nullable = false)
	private String name;

	/** 비밀번호. */
	@Column(nullable = false)
	private String password;

	/** 성별. */
	@Column(length = 5)
	private String gender;

	/** BIRTHDAY. */
	private Date birthday;

	/** 전화. */
	@Column(length = 18)
	private String telNumber;

	/** 주소. */
	@Column(length = 50)
	private String address;

	/** 프로필 사진. */
	@Column
	private String profile;
	
	/** 생성일. */
	@ColumnDefault("SYSDATE")
	@CreationTimestamp
	private LocalDateTime createdAt;

	/** 활성화 여부. */
	@Column
	@ColumnDefault("1")
	private String isactive;

	/** 수정 시간. */
	private LocalDateTime updatedAt;

	/** 수정 여부. */
	@Column
	@ColumnDefault("0")
	private String isupdate;

	/** 삭제날짜. */
	private LocalDateTime deletedAt;

	/** 삭제 여부. */
	@Column
	@ColumnDefault("0")
	private String isdelete;

	/** 소셜 연동 여부. */
	private String issocial;

	/** 소셜 연동 날짜. */
	private LocalDateTime socialAt;

	/** 가이드, 어드민, 유저 인지. */
	@Column(length = 10)
	@ColumnDefault("USER")
	private String role;

	/** 가이드 자격증. */
	private String guidelicense;
	

	/** 로그인 타입 */
	@Column(name = "login_type", nullable = false)
	@ColumnDefault("local")
    private String loginType;

	/** 소셜로그인 어세스 토큰 */
	@Column(name = "sns_access_token", nullable = true)
    private String snsAccessToken;

	
	/** 선호 도시*/
	/*
	@Column(name = "inter_city", nullable = false)
    private String interCity;
	*/
}
